OTHER_FILES += \ 
	"$$unrealRootPath/Engine/Source/Developer/AITestSuite/AITestSuite.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/Android/AndroidDeviceDetection/AndroidDeviceDetection.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/Android/AndroidPlatformEditor/AndroidPlatformEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/Android/AndroidTargetPlatform/AndroidTargetPlatform.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/Android/Android_ATCTargetPlatform/Android_ATCTargetPlatform.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/Android/Android_DXTTargetPlatform/Android_DXTTargetPlatform.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/Android/Android_ES31TargetPlatform/Android_ES31TargetPlatform.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/Android/Android_ETC1TargetPlatform/Android_ETC1TargetPlatform.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/Android/Android_ETC2TargetPlatform/Android_ETC2TargetPlatform.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/Android/Android_PVRTCTargetPlatform/Android_PVRTCTargetPlatform.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/AssetTools/AssetTools.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/AudioFormatADPCM/AudioFormatADPCM.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/AudioFormatOgg/AudioFormatOgg.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/AudioFormatOpus/AudioFormatOpus.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/AutomationController/AutomationController.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/AutomationWindow/AutomationWindow.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/BlankModule/BlankModule.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/CollectionManager/CollectionManager.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/CollisionAnalyzer/CollisionAnalyzer.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/CrashDebugHelper/CrashDebugHelper.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/CrashTracker/CrashTracker.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/DerivedDataCache/DerivedDataCache.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/DesktopPlatform/DesktopPlatform.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/DesktopWidgets/DesktopWidgets.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/DeviceManager/DeviceManager.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/DirectoryWatcher/DirectoryWatcher.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/ExternalImagePicker/ExternalImagePicker.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/FriendsAndChat/FriendsAndChat.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/FunctionalTesting/FunctionalTesting.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/GameplayDebugger/GameplayDebugger.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/GammaUI/GammaUI.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/HTML5/HTML5TargetPlatform/HTML5TargetPlatform.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/HotReload/HotReload.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/ImageCore/ImageCore.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/ImageWrapper/ImageWrapper.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/InternationalizationSettings/InternationalizationSettings.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/LauncherServices/LauncherServices.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/Linux/LinuxNoEditorTargetPlatform/LinuxNoEditorTargetPlatform.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/Linux/LinuxServerTargetPlatform/LinuxServerTargetPlatform.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/Linux/LinuxTargetPlatform/LinuxTargetPlatform.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/LogVisualizer/LogVisualizer.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/Merge/Merge.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/MeshBoneReduction/MeshBoneReduction.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/MeshSimplifier/MeshSimplifier.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/MeshUtilities/MeshUtilities.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/MessageLog/MessageLog.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/ModuleUI/ModuleUI.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/MovieSceneTools/MovieSceneTools.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/OutputLog/OutputLog.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/PackageDependencyInfo/PackageDependencyInfo.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/Profiler/Profiler.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/ProfilerClient/ProfilerClient.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/ProfilerMessages/ProfilerMessages.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/ProfilerService/ProfilerService.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/ProjectLauncher/ProjectLauncher.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/RawMesh/RawMesh.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/RealtimeProfiler/RealtimeProfiler.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/ScreenShotComparison/ScreenShotComparison.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/ScreenShotComparisonTools/ScreenShotComparisonTools.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/SessionFrontend/SessionFrontend.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/SessionMessages/SessionMessages.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/SessionServices/SessionServices.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/Settings/Settings.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/SettingsEditor/SettingsEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/ShaderCompilerCommon/ShaderCompilerCommon.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/ShaderFormatOpenGL/ShaderFormatOpenGL.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/ShaderPreprocessor/ShaderPreprocessor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/SharedSettingsWidgets/SharedSettingsWidgets.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/SimplygonMeshReduction/SimplygonMeshReduction.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/SlateReflector/SlateReflector.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/SourceCodeAccess/SourceCodeAccess.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/SourceControl/SourceControl.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/StandaloneRenderer/StandaloneRenderer.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/SuperSearch/SuperSearch.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/SynthBenchmark/SynthBenchmark.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/TargetDeviceServices/TargetDeviceServices.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/TargetPlatform/TargetPlatform.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/TaskGraph/TaskGraph.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/TextureCompressor/TextureCompressor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/TextureFormatASTC/TextureFormatASTC.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/TextureFormatAndroid/TextureFormatAndroid.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/TextureFormatDXT/TextureFormatDXT.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/TextureFormatIntelISPCTexComp/TextureFormatIntelISPCTexComp.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/TextureFormatPVR/TextureFormatPVR.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/TextureFormatUncompressed/TextureFormatUncompressed.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/Toolbox/Toolbox.Build.cs" \
	"$$unrealRootPath/Engine/Source/Developer/WidgetCarousel/WidgetCarousel.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/ActorPickerMode/ActorPickerMode.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/AddContentDialog/AddContentDialog.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/AnimGraph/AnimGraph.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/BehaviorTreeEditor/BehaviorTreeEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/BlueprintGraph/BlueprintGraph.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/Blutility/Blutility.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/BspMode/BspMode.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/Cascade/Cascade.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/ClassViewer/ClassViewer.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/ComponentVisualizers/ComponentVisualizers.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/ContentBrowser/ContentBrowser.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/CurveAssetEditor/CurveAssetEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/CurveTableEditor/CurveTableEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/DataTableEditor/DataTableEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/DestructibleMeshEditor/DestructibleMeshEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/DetailCustomizations/DetailCustomizations.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/DeviceProfileEditor/DeviceProfileEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/DeviceProfileServices/DeviceProfileServices.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/DistCurveEditor/DistCurveEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/Documentation/Documentation.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/EditorLiveStreaming/EditorLiveStreaming.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/EditorSettingsViewer/EditorSettingsViewer.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/EditorStyle/EditorStyle.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/EditorWidgets/EditorWidgets.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/EnvironmentQueryEditor/EnvironmentQueryEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/FoliageEdit/FoliageEdit.build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/FontEditor/FontEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/GameProjectGeneration/GameProjectGeneration.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/GameplayAbilitiesEditor/GameplayAbilitiesEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/GameplayTagsEditor/GameplayTagsEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/GeometryMode/GeometryMode.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/GraphEditor/GraphEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/HardwareTargeting/HardwareTargeting.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/InputBindingEditor/InputBindingEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/IntroTutorials/IntroTutorials.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/Kismet/Kismet.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/KismetCompiler/KismetCompiler.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/KismetWidgets/KismetWidgets.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/LandscapeEditor/LandscapeEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/Layers/Layers.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/LevelEditor/LevelEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/Levels/Levels.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/MainFrame/MainFrame.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/MaterialEditor/MaterialEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/Matinee/Matinee.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/MeshPaint/MeshPaint.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/NewLevelDialog/NewLevelDialog.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/NewsFeed/NewsFeed.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/NiagaraEditor/NiagaraEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/OnlineBlueprintSupport/OnlineBlueprintSupport.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/PListEditor/PListEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/PackagesDialog/PackagesDialog.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/Persona/Persona.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/PhAT/PhAT.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/PlacementMode/PlacementMode.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/ProjectSettingsViewer/ProjectSettingsViewer.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/ProjectTargetPlatformEditor/ProjectTargetPlatformEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/PropertyEditor/PropertyEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/ReferenceViewer/ReferenceViewer.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/SceneOutliner/SceneOutliner.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/Sequencer/Sequencer.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/SequencerWidgets/SequencerWidgets.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/SoundClassEditor/SoundClassEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/SoundCueEditor/SoundCueEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/SourceControlWindows/SourceControlWindows.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/StaticMeshEditor/StaticMeshEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/StatsViewer/StatsViewer.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/SwarmInterface/SwarmInterface.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/SwarmInterface/DotNET/SwarmInterface.cs" \
	"$$unrealRootPath/Engine/Source/Editor/SwarmInterface/DotNET/Util.cs" \
	"$$unrealRootPath/Engine/Source/Editor/SwarmInterface/DotNET/Properties/AssemblyInfo.cs" \
	"$$unrealRootPath/Engine/Source/Editor/TaskBrowser/TaskBrowser.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/TextureAlignMode/TextureAlignMode.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/TextureEditor/TextureEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/TranslationEditor/TranslationEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/UMGEditor/UMGEditor.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/UndoHistory/UndoHistory.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/UnrealEd/UnrealEd.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/UnrealEdMessages/UnrealEdMessages.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/UserFeedback/UserFeedback.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/ViewportSnapping/ViewportSnapping.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/WorkspaceMenuStructure/WorkspaceMenuStructure.Build.cs" \
	"$$unrealRootPath/Engine/Source/Editor/WorldBrowser/WorldBrowser.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/BlankProgram/BlankProgram.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/BlankProgram/BlankProgram.Target.cs" \
	"$$unrealRootPath/Engine/Source/Programs/BuildPatchTool/BuildPatchTool.Automation.cs" \
	"$$unrealRootPath/Engine/Source/Programs/BuildPatchTool/BuildPatchTool.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/BuildPatchTool/BuildPatchTool.Target.cs" \
	"$$unrealRootPath/Engine/Source/Programs/CrashReporter/CrashReportClient/CrashReportClient.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/CrashReporter/CrashReportClient/CrashReportClient.Target.cs" \
	"$$unrealRootPath/Engine/Source/Programs/CrashReporter/MinidumpDiagnostics/MinidumpDiagnostics.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/CrashReporter/MinidumpDiagnostics/MinidumpDiagnostics.Target.cs" \
	"$$unrealRootPath/Engine/Source/Programs/CrossCompilerTool/CrossCompilerTool.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/CrossCompilerTool/CrossCompilerTool.Target.cs" \
	"$$unrealRootPath/Engine/Source/Programs/ShaderCompileWorker/ShaderCompileWorker.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/ShaderCompileWorker/ShaderCompileWorker.Target.cs" \
	"$$unrealRootPath/Engine/Source/Programs/SlateViewer/SlateViewer.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/SlateViewer/SlateViewer.Target.cs" \
	"$$unrealRootPath/Engine/Source/Programs/SymbolDebugger/SymbolDebugger.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/SymbolDebugger/SymbolDebugger.Target.cs" \
	"$$unrealRootPath/Engine/Source/Programs/TestPAL/TestPAL.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/TestPAL/TestPAL.Target.cs" \
	"$$unrealRootPath/Engine/Source/Programs/UnrealCEFSubProcess/UnrealCEFSubProcess.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/UnrealCEFSubProcess/UnrealCEFSubProcess.Target.cs" \
	"$$unrealRootPath/Engine/Source/Programs/UnrealFileServer/UnrealFileServer.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/UnrealFileServer/UnrealFileServer.Target.cs" \
	"$$unrealRootPath/Engine/Source/Programs/UnrealFrontend/UnrealFrontend.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/UnrealFrontend/UnrealFrontend.Target.cs" \
	"$$unrealRootPath/Engine/Source/Programs/UnrealHeaderTool/UnrealHeaderTool.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/UnrealHeaderTool/UnrealHeaderTool.Target.cs" \
	"$$unrealRootPath/Engine/Source/Programs/UnrealLightmass/UnrealLightmass.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/UnrealLightmass/UnrealLightmass.Target.cs" \
	"$$unrealRootPath/Engine/Source/Programs/UnrealPak/UnrealPak.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/UnrealPak/UnrealPak.Target.cs" \
	"$$unrealRootPath/Engine/Source/Programs/UnrealSync/UnrealSync.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/UnrealSync/UnrealSync.Target.cs" \
	"$$unrealRootPath/Engine/Source/Programs/UnrealVersionSelector/UnrealVersionSelector.Build.cs" \
	"$$unrealRootPath/Engine/Source/Programs/UnrealVersionSelector/UnrealVersionSelector.Target.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/AIModule/AIModule.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Advertising/Advertising/Advertising.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Advertising/Android/AndroidAdvertising/AndroidAdvertising.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Analytics/Analytics/Analytics.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Analytics/AnalyticsET/AnalyticsET.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Analytics/AnalyticsMulticast/AnalyticsMulticast.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Analytics/AnalyticsSwrve/AnalyticsSwrve.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Android/AndroidAudio/AndroidAudio.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Android/AndroidRuntimeSettings/AndroidRuntimeSettings.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/AppFramework/AppFramework.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/AssetRegistry/AssetRegistry.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/AutomationMessages/AutomationMessages.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/AutomationWorker/AutomationWorker.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/CEF3Utils/CEF3Utils.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Core/Core.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/CoreUObject/CoreUObject.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/DatabaseSupport/DatabaseSupport.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/EmptyRHI/EmptyRHI.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Engine/Engine.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/EngineMessages/EngineMessages.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/EngineSettings/EngineSettings.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/GameLiveStreaming/GameLiveStreaming.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/GameMenuBuilder/GameMenuBuilder.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/GameplayAbilities/GameplayAbilities.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/GameplayTags/GameplayTags.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/HTML5/HTML5Audio/HTML5Audio.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/HTML5/HTML5JS/HTML5JS.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/HTML5/Simulator/HTML5Win32/HTML5Win32.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/HTTPChunkInstaller/HTTPChunkInstaller.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/HeadMountedDisplay/HeadMountedDisplay.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/IPC/IPC.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/InputCore/InputCore.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/InputDevice/InputDevice.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Internationalization/Internationalization.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Json/Json.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/JsonUtilities/JsonUtilities.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Landscape/Landscape.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Launch/Launch.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/LauncherAutomatedService/LauncherAutomatedService.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Linux/ALAudio/ALAudio.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Linux/SteamController/SteamController.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Media/Media.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/MediaAssets/MediaAssets.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Messaging/Messaging.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/MoviePlayer/MoviePlayer.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/MovieSceneCore/MovieSceneCore.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/MovieSceneCoreTypes/MovieSceneCoreTypes.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Navmesh/Navmesh.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/NetworkFile/NetworkFile.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/NetworkFileSystem/NetworkFileSystem.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Networking/Networking.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/NullDrv/NullDrv.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Online/Android/OnlineSubsystemGooglePlay/OnlineSubsystemGooglePlay.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Online/BuildPatchServices/BuildPatchServices.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Online/HTTP/HTTP.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Online/OnlineSubsystem/OnlineSubsystem.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Online/OnlineSubsystemAmazon/OnlineSubsystemAmazon.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Online/OnlineSubsystemFacebook/OnlineSubsystemFacebook.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Online/OnlineSubsystemNull/OnlineSubsystemNull.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Online/OnlineSubsystemSteam/OnlineSubsystemSteam.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Online/OnlineSubsystemUtils/OnlineSubsystemUtils.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Online/Voice/Voice.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/OpenGLDrv/OpenGLDrv.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/PakFile/PakFile.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/PhysXFormats/PhysXFormats.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Projects/Projects.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/RHI/RHI.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/RenderCore/RenderCore.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Renderer/Renderer.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/SQLiteSupport/SQLiteSupport.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/SandboxFile/SandboxFile.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Serialization/Serialization.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/ShaderCore/ShaderCore.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Slate/Slate.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/SlateCore/SlateCore.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/SlateRHIRenderer/SlateRHIRenderer.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/Sockets/Sockets.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/StreamingFile/StreamingFile.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/StreamingPauseRendering/StreamingPauseRendering.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/UE4Game/UE4Game.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/UMG/UMG.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/VectorVM/VectorVM.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/WebBrowser/WebBrowser.Build.cs" \
	"$$unrealRootPath/Engine/Source/Runtime/XmlParser/XmlParser.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/2D/Paper2D/Source/Paper2D/Paper2D.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/2D/Paper2D/Source/Paper2DEditor/Paper2DEditor.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/2D/Paper2D/Source/PaperJsonImporter/PaperJsonImporter.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/2D/Paper2D/Source/PaperTiledImporter/PaperTiledImporter.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/2D/Paper2D/Source/SmartSnapping/SmartSnapping.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Developer/BlankPlugin/Source/BlankPlugin/BlankPlugin.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Developer/GitSourceControl/Source/GitSourceControl/GitSourceControl.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Developer/KDevelopSourceCodeAccess/Source/KDevelopSourceCodeAccess/KDevelopSourceCodeAccess.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Developer/PerforceSourceControl/Source/PerforceSourceControl/PerforceSourceControl.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Developer/SubversionSourceControl/Source/SubversionSourceControl/SubversionSourceControl.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Developer/UObjectPlugin/Source/UObjectPlugin/UObjectPlugin.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Editor/EpicSurvey/Source/EpicSurvey/EpicSurvey.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Editor/PluginsEditor/Source/PluginsEditor/PluginsEditor.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Editor/SpeedTreeImporter/Source/SpeedTreeImporter/SpeedTreeImporter.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Experimental/BlueprintStats/Source/BlueprintStats/BlueprintStats.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Experimental/CharacterAI/Source/CharacterAI/CharacterAI.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Experimental/CodeView/Source/CodeView/CodeView.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Experimental/LiveEditor/Source/LiveEditor/LiveEditor.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Experimental/Phya/Source/Phya/Phya.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Experimental/SimpleHMD/Source/SimpleHMD/SimpleHMD.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Experimental/SteamVR/Source/SteamVR/SteamVR.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Media/AndroidMedia/Source/AndroidMedia/AndroidMedia.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Media/AvfMedia/Source/AvfMedia/AvfMedia.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Media/MediaPlayerEditor/Source/MediaPlayerEditor/MediaPlayerEditor.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Messaging/MessagingDebugger/Source/MessagingDebugger/MessagingDebugger.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Messaging/ShmMessaging/Source/ShmMessaging/ShmMessaging.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Messaging/UdpMessaging/Source/UdpMessaging/UdpMessaging.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Runtime/Advertising/IOSTapJoy/Source/IOSTapJoy/IOSTapJoy.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Runtime/Analytics/AnalyticsBlueprintLibrary/Source/AnalyticsBlueprintLibrary/AnalyticsBlueprintLibrary.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Runtime/Analytics/Apsalar/IOSApsalar/Source/IOSApsalar/IOSApsalar.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Runtime/Analytics/FileLogging/Source/FileLogging/FileLogging.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Runtime/AndroidDeviceProfileSelector/Source/AndroidDeviceProfileSelector/AndroidDeviceProfileSelector.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Runtime/AndroidMoviePlayer/Source/AndroidMoviePlayer/AndroidMoviePlayer.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Runtime/CableComponent/Source/CableComponent/CableComponent.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Runtime/CustomMeshComponent/Source/CustomMeshComponent/CustomMeshComponent.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Runtime/ExampleDeviceProfileSelector/Source/ExampleDeviceProfileSelector/ExampleDeviceProfileSelector.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Runtime/GearVR/Source/GearVR/GearVR.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Runtime/LeapMotionController/Source/LeapMotionController/LeapMotionController.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Runtime/LiveEditorListenServer/Source/LiveEditorListenServer/LiveEditorListenServer.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Runtime/OculusRift/Source/OculusRift/OculusRift.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Runtime/SoundMod/Source/SoundMod/SoundMod.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Runtime/SoundMod/Source/SoundModImporter/SoundModImporter.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Runtime/SoundVisualizations/Source/SoundVisualizations/SoundVisualizations.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Runtime/TwitchLiveStreaming/Source/TwitchLiveStreaming/TwitchLiveStreaming.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/ScriptGeneratorPlugin/Source/ScriptGeneratorPlugin/ScriptGeneratorPlugin.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/ScriptPlugin/Source/ScriptEditorPlugin/ScriptEditorPlugin.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/ScriptPlugin/Source/ScriptPlugin/ScriptPlugin.Build.cs" \
	"$$unrealRootPath/Engine/Plugins/Slate/SlateRemote/Source/SlateRemote/SlateRemote.Build.cs" \
	"$$FPSProjectRootPath/Source/FPSProject/FPSProject.Build.cs" \
 

